application: ceg-86
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /.*
  script: ceg-86.py

builtins:
- remote_api: on
- datastore_admin: on
